name = "draft-api"
main = "src/index.ts"
compatibility_date = "2025-08-05"

[triggers]
crons = ["0 12 * * 3"] # Every Wednesday at 12:00 UTC

[[d1_databases]]
binding = "DB"
database_name = "draft-db"
database_id = "9eb7efca-2e7d-46e3-b8de-16f7cc02f2bd" 